### ISSUE TITLE
etcd-backed event values integration test flaky

### ISSUE THREAD

**Issue by lorenz** [monogon-dev/monogon#120]
```
$ bazel test --runs_per_test=100 //metropolis/pkg/event/etcd:etcd_test
//metropolis/pkg/event/etcd:etcd_test                                    FAILED in 50 out of 100 in 81.8s
  Stats over 100 runs: max = 81.8s, min = 6.5s, avg = 47.9s, dev = 26.2s
```

Breakdown:
```
FAIL: TestCancelOnGet  37 / 100
FAIL: TestClientPartition 5 / 100
FAIL: TestDecoder 10 / 100
FAIL: TestSimpleRange 6 / 100
```

Also on 3 runs I observed the following panic:
```
panic: multiple keys in nonranged value

goroutine 1753 [running]:
source.monogon.dev/metropolis/pkg/event/etcd.(*watcher).Get(0xc003ed2ea0, {0x1098330, 0xc004087040}, {0x0, 0x0, 0xc00048cfd0})
        metropolis/pkg/event/etcd/etcd.go:414 +0x4f9
source.monogon.dev/metropolis/pkg/event/etcd.wait.func1()
        metropolis/pkg/event/etcd/etcd_test.go:197 +0xb2
created by source.monogon.dev/metropolis/pkg/event/etcd.wait
        metropolis/pkg/event/etcd/etcd_test.go:195 +0x10f
```

**Comment by q3k** [comment]
This is likely related to having bumped etcd in The Big Bump Change (review.monogon.dev/639). I'll take a look at it.

**Comment by q3k** [comment]
https://review.monogon.dev/c/monogon/+/653

https://review.monogon.dev/c/monogon/+/654

**Comment by q3k** [comment]
Should be fixed by the above.
