### ISSUE TITLE
metroctl: node update all panics

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#290]
After updating one node is crashes:

```
panic: runtime error: index out of range [0] with length 0

goroutine 45 [running]:
main.glob..func4.1(0xc0001fcb80)
        metropolis/cli/metroctl/cmd_node.go:182 +0xb15
created by main.glob..func4 in goroutine 1
        metropolis/cli/metroctl/cmd_node.go:152 +0x739
```

**Comment by lorenz** [comment]
Happens because the check that there are nodes logs the issue, but does not actually skip over the code which uses the node. I'll fix it.

**Comment by lorenz** [comment]
https://review.monogon.dev/c/monogon/+/2834
