### ISSUE TITLE
Timeout for go mod operations in fietsje

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#39]
(originally reported by @q3k in T806)

```
2020/06/19 19:00:06 "github.com/cilium/cilium": parsing go.sum
--
2020/06/19 19:18:24 go mod returned: ""
panic: could not get transitive deps for "github.com/volatiletech/sqlboiler/v4": could not download: go mod failed: signal: terminated
 
goroutine 1 [running]:
main.(*planner).collectInternal(0xc0001567a0, 0x5f05dc, 0x24, 0x5e6dd1, 0x6, 0xc0000c3700, 0x0, 0x0, 0x0, 0x32)
build/fietsje/planner.go:72 +0x87e
main.(*planner).collect(...)
build/fietsje/planner.go:35
main.depsSQLBoiler(0xc0001567a0)
build/fietsje/deps_sqlboiler.go:4 +0x83
main.main()
build/fietsje/main.go:53 +0x3cc
```

... or better: implement retry handling.

**Comment by lorenz** [comment]
fietsje was dropped a long time ago, closing
