### ISSUE TITLE
panic: interface conversion: interface {} is nil, not *curator.Node

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#75]
`bazel run :launch` on e306d780504ae3ddfad3eb852c7adc5ec9757d89:

```
root.curator                     I0908 07:03:46.616078 curator.go:264] Election watcher: this node's curator is a follower
root.curator.listener.dispatcher I0908 07:03:46.617180 listener.go:147] Dispatcher switching over to follower
panic: interface conversion: interface {} is nil, not *curator.Node

goroutine 336 [running]:
source.monogon.dev/metropolis/node/core/curator.(*leaderCurator).Watch(0xc000b7c680, 0xc0004dfe40, 0x268fac0, 0xc000d2af40, 0x0, 0x0)
	metropolis/node/core/curator/impl_leader_curator.go:48 +0x5de
source.monogon.dev/metropolis/node/core/curator.(*listener).Watch.func1(0x2673bc0, 0xc0004dff40, 0x2668c80, 0xc000b7c680, 0x2673bc0, 0xc0004dff40)
	metropolis/node/core/curator/listener.go:313 +0xe7
source.monogon.dev/metropolis/node/core/curator.(*listener).callImpl(0xc000632e70, 0x2672540, 0xc00104ca20, 0xc000541bf0, 0xc000541c10, 0x40cd08)
	metropolis/node/core/curator/listener.go:267 +0xc0
source.monogon.dev/metropolis/node/core/curator.(*listener).Watch(0xc000632e70, 0xc0004dfe40, 0x268fb80, 0xc000b1a900, 0xc000632e70, 0x20)
	metropolis/node/core/curator/listener.go:318 +0x7a
source.monogon.dev/metropolis/node/core/curator/proto/api._Curator_Watch_Handler(0x2110080, 0xc000632e70, 0x26869a0, 0xc000137bc0, 0x3d53c68, 0xc00102a500)
	bazel-out/k8-fastbuild-ST-3891b650e255/bin/metropolis/node/core/curator/proto/api/api_go_proto_/source.monogon.dev/metropolis/node/core/curator/proto/api/api.pb.go:487 +0x109
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000090b60, 0x26977a0, 0xc000de5800, 0xc00102a500, 0xc000acbe00, 0x37d4240, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1329 +0xcbd
google.golang.org/grpc.(*Server).handleStream(0xc000090b60, 0x26977a0, 0xc000de5800, 0xc00102a500, 0x0)
	external/org_golang_google_grpc/server.go:1409 +0xc66
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00054bec0, 0xc000090b60, 0x26977a0, 0xc000de5800, 0xc00102a500)
	external/org_golang_google_grpc/server.go:746 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:744 +0xa1
```

Full log: https://gist.github.com/leoluk/17bace1a2d95009e597ef62edaaabfdd

2nd attempt worked.

**Comment by q3k** [comment]
https://review.monogon.dev/c/monogon/+/326
